# Generated by Django 4.0.4 on 2022-05-23 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_url', models.CharField(max_length=150)),
                ('about_project', models.TextField(max_length=400)),
                ('complexity', models.CharField(blank=True, choices=[('EZ', 'easy'), ('NO', 'normal'), ('HA', 'hard')], max_length=2)),
                ('img_project', models.ImageField(default=True, upload_to='img/project')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.owner')),
            ],
        ),
    ]
